[hooks]
"after:git" = ["git checkout master", "git merge develop", "./build.sh --full"]
"after:release" = ["git checkout develop"]

[git]
"commitMessage" = "Диплом: версия ${version}"
"commit" = false

[github]
"releaseName" = "Диплом: версия ${version}"
"release" = true
"assets" = ["out.pdf"]
