[hooks]
"before:init" = ["git checkout master", "git merge develop", "./build.sh --full"]
"after:release" = ["git checkout develop"]

[git]
"commitMessage" = "Диплом: версия ${version}"
"requireBranch" = "master"

[github]
"release" = true
"assets" = ["out.pdf"]
