[hooks]
"before:init" = ["./build.sh --full"]
"after:init" = [
    "git checkout master",
    "git merge --ff develop",
]
"after:release" = [
    "git log --pretty=format:'%s' ${latestVersion}...HEAD --grep='+ ' --reverse > changelog.txt",
    "git checkout develop",
]

[git]
"changelog" = "./generate_changelog.sh ${latestTag} HEAD"
"commitMessage" = "Диплом: версия ${version}"
"commit" = false

[github]
"releaseName" = "Диплом: версия ${version}"
"release" = true
"assets" = ["out/full.pdf", "slides/slides.pdf"]
"draft" = true
