[hooks]
"before:init" = ["./build.sh --full"]
"after:init" = [
    "git checkout master",
    "git merge --ff develop",
]
"after:release" = [
    "git log --pretty=format:'%s' ${latestVersion}...HEAD --grep='+ ' --reverse > changelog.txt",
    "git checkout develop",
]

[git]
"changelog" = '''
    echo "### Плюсы\n" &&
    git log --pretty=format:'%s (%h)' ${latestTag}...HEAD --grep='+ ' --reverse &&
    echo "\n\n### Минусы\n" &&
    git log --pretty=format:'%s (%h)' ${latestTag}...HEAD --grep='- ' --reverse &&
    echo "\n\n### Подводные камни\n" &&
    git log --pretty=format:'%s (%h)' ${latestTag}...HEAD --grep='+ ' --grep='- ' --invert-grep
'''
"commitMessage" = "Диплом: версия ${version}"
"commit" = false

[github]
"releaseName" = "Диплом: версия ${version}"
"release" = true
"assets" = ["out.pdf"]
"draft" = true
